baseURL = "http://blog.leaver.me/"
languageCode = "zh-CN"
title = "bystander's blog"
theme = "jane"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "leaverme"
googleAnalytics = "UA-30961201-3"
summaryLength = 140
defaultContentLanguage = "zh-cn" 

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  homeFullContent = false
  rssFullContent = true
  description = "寻找窄门"
  logo = "images/author.jpg"
  favicon = "images/favicon.ico"
  dateFormatToUse = "2006-01-02"
  moreMeta = true
  since = "2012"
  toc = true 
  photoswipe = true

[params.social]
    g-github = "https://github.com/leizhiyuan"

[permalinks]
  post = "/:year/:month/:day/:title/"
[author]
  name = "bystander"
  website = "blog.leaver.me"
  github = "leizhiyuan"
[menu]
[[menu.main]] 
      name = "主页"
      weight = 10
      identifier = "home"
      url = "/"
[[menu.main]]
      name = "归档"
      weight = 20
      identifier = "archives"
      url = "/post/"      
[[menu.main]]
      name = "标签"
      weight = 30
      identifier = "tags"
      url = "/tags/"
[[menu.main]]
      name = "目录"
      weight = 40
      identifier = "categories"
      url = "/categories/"
[[menu.main]]
      name = "关于我"
      weight = 50
      identifier = "about"
      url = "/about/"