baseURL = "http://leaver.me/"
languageCode = "zh-CN"
title = "bystander's blog"
theme = "maupassant"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "leaverme"
googleAnalytics = "30961201"
summaryLength = 140

[Params]
  subtitle = "寻找窄门"
  logo = "images/author.jpg"
  favicon = "images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = false
  localSearch = true

  [[Params.links]]
    title = "C++爱好者博客"
    name = "C++爱好者博客"
    url = "https://www.cppfans.org/"

  [[Params.links]]
    title = "KL，每天进步一点点"
    name = "KL，每天进步一点点"
    url = "http://www.kailing.pub"


[permalinks]
  post = "/:year/:month/:day/:title/"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "bystander"
  website = "leaver.me"
  #email = "youremail@domain.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "leizhiyuan"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
[menu]
  [[menu.main]]
      identifier = "categories"
      name = "目录"
      url = "/categories"
      weight = 2

  [[menu.main]]
      identifier = "about"
      name = "关于我"
      url = "/about/"
      weight = 5
